name: Setup CI container
description: Reusable container setup
inputs:
  php-version:
    required: true
  symfony-version:
    required: true
  cache-key-suffix:
    required: true
outputs:
  php-version:
    description: "Used PHP version"
    value: ${{ inputs.php-version }}
runs:
  using: composite
  steps:
    - name: Setup PHP
      id: setup-php
      uses: shivammathur/setup-php@v2
      with:
          php-version: ${{ inputs.php-version }}
          extensions: json, libxml, pdo, pdo_mysql, pdo_sqlite, pdo_pgsql, sqlite3
          coverage: pcov

    - name: Composer get cache directory
      id: composer-cache
      shell: bash
      run: |
          echo "cache_files_dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"

    - name: Composer cache
      uses: actions/cache@v4.2.0
      with:
          path: ${{ steps.composer-cache.outputs.cache_files_dir }}
          key: ${{ runner.os }}-composer-php:${{ inputs.php-version }}-symfony:${{ inputs.symfony-version }}-${{ inputs.cache-key-suffix }}
          restore-keys: |
              ${{ runner.os }}-composer-php:${{ inputs.php-version }}-symfony:${{ inputs.symfony-version }}
              ${{ runner.os }}-composer-php:${{ inputs.php-version }}-
              ${{ runner.os }}-composer-

    - name: Composer validate
      run: composer validate
      shell: bash

    - name: Composer install
      run: composer install --prefer-dist --no-interaction
      shell: bash
